name: Repo Cleanup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to clean'
        required: true
        default: 'main'
      keep_workflows:
        description: 'Keep .github/workflows? (true/false)'
        required: false
        default: 'true'

permissions:
  contents: write

jobs:
  wipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Remove files
        run: |
          if [ "${{ inputs.keep_workflows }}" = "true" ]; then
            find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".github" -exec rm -rf {} +
            if [ -d ".github" ]; then
              find .github -mindepth 1 -maxdepth 1 ! -name "workflows" -exec rm -rf {} +
            fi
          else
            find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +
          fi

      - name: Commit deletions
        run: |
          git add -A
          git commit -m "Remove all files"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Empty commit to reset repository"

      - name: Push changes
        run: |
          git push origin HEAD:${{ inputs.branch }}
